/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrame;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author raino13
 */
public class DeleteAdPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAdPanel
     */
    public DeleteAdPanel() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        button1 = new java.awt.Button();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        importPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        targetHouseIdField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        targetPasswordField = new javax.swing.JPasswordField();
        importButton = new javax.swing.JButton();
        importErrorLabel = new javax.swing.JLabel();
        importSuccessfullLabel = new javax.swing.JLabel();

        jButton11.setText("jButton1");

        jButton9.setText("jButton1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.setLabel("button1");

        setBackground(new java.awt.Color(34, 49, 63));
        setForeground(new java.awt.Color(34, 49, 63));
        setMinimumSize(new java.awt.Dimension(954, 389));
        setPreferredSize(new java.awt.Dimension(954, 448));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("HandelGotDLig", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delete Ad");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        jSeparator15.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator15.setForeground(new java.awt.Color(102, 255, 51));
        add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 940, 10));

        importPanel.setBackground(new java.awt.Color(34, 49, 63));
        importPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("House id");
        importPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        jSeparator12.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator12.setForeground(new java.awt.Color(102, 255, 51));
        importPanel.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 10));

        targetHouseIdField.setBackground(new java.awt.Color(34, 49, 63));
        targetHouseIdField.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        targetHouseIdField.setForeground(new java.awt.Color(255, 255, 255));
        targetHouseIdField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        importPanel.add(targetHouseIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, 20));

        jLabel17.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Password");
        importPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 80, -1));

        jSeparator13.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator13.setForeground(new java.awt.Color(102, 255, 51));
        importPanel.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 180, 10));

        targetPasswordField.setBackground(new java.awt.Color(34, 49, 63));
        targetPasswordField.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        targetPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        targetPasswordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        importPanel.add(targetPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 180, 20));

        importButton.setBackground(new java.awt.Color(102, 0, 0));
        importButton.setFont(new java.awt.Font("HandelGotDLig", 0, 14)); // NOI18N
        importButton.setForeground(new java.awt.Color(255, 255, 255));
        importButton.setText("Delete");
        importButton.setToolTipText("");
        importButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        importButton.setFocusPainted(false);
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });
        importPanel.add(importButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 90, 30));

        importErrorLabel.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        importErrorLabel.setForeground(new java.awt.Color(51, 255, 255));
        importErrorLabel.setText("delete your data");
        importPanel.add(importErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 280, 30));

        add(importPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 840, 70));

        importSuccessfullLabel.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        importSuccessfullLabel.setForeground(new java.awt.Color(51, 255, 255));
        importSuccessfullLabel.setText("data deleted !");
        add(importSuccessfullLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        // TODO add your handling code here:              
        deleteData();
    }//GEN-LAST:event_importButtonActionPerformed
  
    public void clearFields(){
        targetHouseIdField.setText("");
        targetHouseId = null;
        targetPasswordField.setText("");
        targetPassword = null;
        importPanel.setVisible(true);
    }
    
    private void deleteComand(){
        
        Connection myConnection = null;
        PreparedStatement myStatement = null;
        String sql = "Delete from houseAd where houseId=?";
        
        try{
            
            myConnection = DriverManager.getConnection("jdbc:derby://localhost:1527/RentHouseDatabase", "rain013", "oopfinalproject");
            
            myStatement = myConnection.prepareStatement(sql);
            
            myStatement.setString(1, targetHouseIdField.getText());            
            
            myStatement.executeUpdate();
            
            System.out.println("old data deleted");
            
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    private void deleteData(){
        Connection myConnection = null;
        Statement myStatement  = null;
        ResultSet myResultSet = null;
        ResultSetMetaData myMetaData = null;
        
        
        String sql = "select * from houseAd";
        
        try{
            // get connection to database
            myConnection = DriverManager.getConnection("jdbc:derby://localhost:1527/RentHouseDatabase", "rain013", "oopfinalproject");
            
            // creaTe statement
            myStatement = myConnection.createStatement();
            
            myResultSet = myStatement.executeQuery(sql);
            
            myMetaData = myResultSet.getMetaData();
            
            int columnCount = myMetaData.getColumnCount();
            
            targetHouseId = targetHouseIdField.getText();
            targetPassword = targetPasswordField.getText();
            
            boolean found = false;
            
            while(myResultSet.next())
            {
                if(targetHouseId.equals(myResultSet.getString("houseId")) && targetPassword.equals(myResultSet.getString("password"))){                                        
                    found = true;                 
                }
            }
            
            if(found == true){
                importPanel.setVisible(false);
                deleteComand();
            }
            
            if(found == false){
                importErrorLabel.setText("wrong username or password !");
            }
            
           
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        
    }
         
    private String imagePathOne, imagePathTwo, imagePathThree, adType, customerType, targetHouseId, targetPassword;
    private ButtonGroup bg1, bg2;
    private Blob blobOne, blobTwo, blobThree;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JButton importButton;
    private javax.swing.JLabel importErrorLabel;
    private javax.swing.JPanel importPanel;
    private javax.swing.JLabel importSuccessfullLabel;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JTextField targetHouseIdField;
    private javax.swing.JPasswordField targetPasswordField;
    // End of variables declaration//GEN-END:variables
}
