/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrame;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author raino13
 */
public class EditAdPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAdPanel
     */
    public EditAdPanel() {
        initComponents();
        buttonGroup();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        button1 = new java.awt.Button();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        titleField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        areaField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        cityField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        roomsComboBox = new javax.swing.JComboBox<>();
        belconyComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        bathroomsComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        floorNoComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        descriptionField = new java.awt.TextArea();
        jLabel11 = new javax.swing.JLabel();
        forSaleRadioButton = new javax.swing.JRadioButton();
        forRentRadioButton = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        ownerNameField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        contactNoField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        streetField = new javax.swing.JTextField();
        postcodeField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        imageLabelOne = new javax.swing.JLabel();
        imageBrowseButtonOne = new javax.swing.JButton();
        imageLabelTwo = new javax.swing.JLabel();
        imageBrowseButtonTwo = new javax.swing.JButton();
        imageLabelThree = new javax.swing.JLabel();
        imageBrowseButtonThee = new javax.swing.JButton();
        monthComboBox = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        familyRadioButton = new javax.swing.JRadioButton();
        bachelorRadioButton = new javax.swing.JRadioButton();
        bothRadioButton = new javax.swing.JRadioButton();
        jSeparator14 = new javax.swing.JSeparator();
        imageDeleteButtonOne = new javax.swing.JButton();
        imageDeleteButtonTwo = new javax.swing.JButton();
        imageDeleteButtonThree = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JSeparator();
        importPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        targetHouseIdField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        targetPasswordField = new javax.swing.JPasswordField();
        importButton = new javax.swing.JButton();
        importErrorLabel = new javax.swing.JLabel();
        submitButton1 = new javax.swing.JButton();
        jLabel244 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        houseIdField = new javax.swing.JTextField();
        jLabel4545 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        passwordField = new javax.swing.JPasswordField();
        importSuccessfullLabel = new javax.swing.JLabel();

        jButton11.setText("jButton1");

        jButton9.setText("jButton1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.setLabel("button1");

        setBackground(new java.awt.Color(34, 49, 63));
        setForeground(new java.awt.Color(34, 49, 63));
        setMinimumSize(new java.awt.Dimension(954, 389));
        setPreferredSize(new java.awt.Dimension(954, 448));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("HandelGotDLig", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Edit Ad");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Description");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 100, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator3.setForeground(new java.awt.Color(102, 255, 51));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 200, 10));

        titleField.setBackground(new java.awt.Color(34, 49, 63));
        titleField.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        titleField.setForeground(new java.awt.Color(255, 255, 255));
        titleField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(titleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 200, 20));

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Area");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 50, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator4.setForeground(new java.awt.Color(102, 255, 51));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 200, 10));

        areaField.setBackground(new java.awt.Color(34, 49, 63));
        areaField.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        areaField.setForeground(new java.awt.Color(255, 255, 255));
        areaField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(areaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, 20));

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("City");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 40, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator5.setForeground(new java.awt.Color(102, 255, 51));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, 10));

        cityField.setBackground(new java.awt.Color(34, 49, 63));
        cityField.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        cityField.setForeground(new java.awt.Color(255, 255, 255));
        cityField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(cityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 200, 20));

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Street address");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator6.setForeground(new java.awt.Color(102, 255, 51));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 200, 10));

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Postcode");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 70, -1));

        jSeparator7.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator7.setForeground(new java.awt.Color(102, 255, 51));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 200, 10));

        roomsComboBox.setBackground(new java.awt.Color(51, 51, 51));
        roomsComboBox.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        roomsComboBox.setForeground(new java.awt.Color(34, 49, 63));
        roomsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        add(roomsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 90, -1));

        belconyComboBox.setBackground(new java.awt.Color(51, 51, 51));
        belconyComboBox.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        belconyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        add(belconyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 90, -1));

        jLabel8.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Belcony");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 70, -1));

        bathroomsComboBox.setBackground(new java.awt.Color(51, 51, 51));
        bathroomsComboBox.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        bathroomsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        add(bathroomsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 90, -1));

        jLabel9.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Bathrooms");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 100, -1));

        floorNoComboBox.setBackground(new java.awt.Color(51, 51, 51));
        floorNoComboBox.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        floorNoComboBox.setMaximumRowCount(5);
        floorNoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        add(floorNoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 90, -1));

        jLabel10.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Floor no.");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 80, -1));

        descriptionField.setBackground(new java.awt.Color(34, 49, 63));
        descriptionField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        descriptionField.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        descriptionField.setForeground(new java.awt.Color(255, 255, 255));
        add(descriptionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 190, 110));

        jLabel11.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Title");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, -1));

        forSaleRadioButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        forSaleRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        forSaleRadioButton.setText("For sale");
        forSaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forSaleRadioButtonActionPerformed(evt);
            }
        });
        add(forSaleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        forRentRadioButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        forRentRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        forRentRadioButton.setText("For rent");
        forRentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forRentRadioButtonActionPerformed(evt);
            }
        });
        add(forRentRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Price in taka");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 120, -1));

        jLabel13.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Your name");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 90, -1));

        jSeparator9.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator9.setForeground(new java.awt.Color(102, 255, 51));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 180, 10));

        ownerNameField.setBackground(new java.awt.Color(34, 49, 63));
        ownerNameField.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        ownerNameField.setForeground(new java.awt.Color(255, 255, 255));
        ownerNameField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(ownerNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 180, 20));

        jLabel14.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Em@il");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 60, -1));

        jSeparator10.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator10.setForeground(new java.awt.Color(102, 255, 51));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 180, 10));

        contactNoField.setBackground(new java.awt.Color(34, 49, 63));
        contactNoField.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        contactNoField.setForeground(new java.awt.Color(255, 255, 255));
        contactNoField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(contactNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 180, 20));

        jLabel15.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Contact no.");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 90, -1));

        jSeparator11.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator11.setForeground(new java.awt.Color(102, 255, 51));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 180, 10));

        streetField.setBackground(new java.awt.Color(34, 49, 63));
        streetField.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        streetField.setForeground(new java.awt.Color(255, 255, 255));
        streetField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(streetField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 200, 20));

        postcodeField.setBackground(new java.awt.Color(34, 49, 63));
        postcodeField.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        postcodeField.setForeground(new java.awt.Color(255, 255, 255));
        postcodeField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(postcodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 200, 20));

        emailField.setBackground(new java.awt.Color(34, 49, 63));
        emailField.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        emailField.setForeground(new java.awt.Color(255, 255, 255));
        emailField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 180, 20));

        jLabel18.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("Rooms");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 40, -1));

        priceField.setBackground(new java.awt.Color(34, 49, 63));
        priceField.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        priceField.setForeground(new java.awt.Color(255, 255, 255));
        priceField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 160, 20));

        imageLabelOne.setBackground(new java.awt.Color(255, 255, 255));
        imageLabelOne.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        imageLabelOne.setForeground(new java.awt.Color(153, 153, 153));
        imageLabelOne.setText(" no image");
        imageLabelOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(imageLabelOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 80, 70));

        imageBrowseButtonOne.setBackground(new java.awt.Color(0, 51, 102));
        imageBrowseButtonOne.setFont(new java.awt.Font("HandelGotDLig", 0, 14)); // NOI18N
        imageBrowseButtonOne.setForeground(new java.awt.Color(255, 255, 255));
        imageBrowseButtonOne.setText("+");
        imageBrowseButtonOne.setFocusPainted(false);
        imageBrowseButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageBrowseButtonOneActionPerformed(evt);
            }
        });
        add(imageBrowseButtonOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 150, -1, -1));

        imageLabelTwo.setBackground(new java.awt.Color(255, 255, 255));
        imageLabelTwo.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        imageLabelTwo.setForeground(new java.awt.Color(153, 153, 153));
        imageLabelTwo.setText(" no image");
        imageLabelTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(imageLabelTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 80, 70));

        imageBrowseButtonTwo.setBackground(new java.awt.Color(0, 51, 102));
        imageBrowseButtonTwo.setFont(new java.awt.Font("HandelGotDLig", 0, 14)); // NOI18N
        imageBrowseButtonTwo.setForeground(new java.awt.Color(255, 255, 255));
        imageBrowseButtonTwo.setText("+");
        imageBrowseButtonTwo.setFocusPainted(false);
        imageBrowseButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageBrowseButtonTwoActionPerformed(evt);
            }
        });
        add(imageBrowseButtonTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, -1, -1));

        imageLabelThree.setBackground(new java.awt.Color(255, 255, 255));
        imageLabelThree.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        imageLabelThree.setForeground(new java.awt.Color(153, 153, 153));
        imageLabelThree.setText(" no image");
        imageLabelThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(imageLabelThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 80, 70));

        imageBrowseButtonThee.setBackground(new java.awt.Color(0, 51, 102));
        imageBrowseButtonThee.setFont(new java.awt.Font("HandelGotDLig", 0, 14)); // NOI18N
        imageBrowseButtonThee.setForeground(new java.awt.Color(255, 255, 255));
        imageBrowseButtonThee.setText("+");
        imageBrowseButtonThee.setFocusPainted(false);
        imageBrowseButtonThee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageBrowseButtonTheeActionPerformed(evt);
            }
        });
        add(imageBrowseButtonThee, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 310, -1, -1));

        monthComboBox.setBackground(new java.awt.Color(51, 51, 51));
        monthComboBox.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        monthComboBox.setMaximumRowCount(5);
        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "June", "July", "August", "September", "Octeber", "November", "December" }));
        add(monthComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 90, -1));

        jLabel19.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("Time");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 80, -1));

        familyRadioButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        familyRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        familyRadioButton.setText("Family");
        familyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familyRadioButtonActionPerformed(evt);
            }
        });
        add(familyRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        bachelorRadioButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        bachelorRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        bachelorRadioButton.setText("Bachelor");
        bachelorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bachelorRadioButtonActionPerformed(evt);
            }
        });
        add(bachelorRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        bothRadioButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        bothRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        bothRadioButton.setText("Both");
        bothRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bothRadioButtonActionPerformed(evt);
            }
        });
        add(bothRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        jSeparator14.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator14.setForeground(new java.awt.Color(102, 255, 51));
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 160, 10));

        imageDeleteButtonOne.setBackground(new java.awt.Color(102, 0, 0));
        imageDeleteButtonOne.setFont(new java.awt.Font("HandelGotDLig", 0, 14)); // NOI18N
        imageDeleteButtonOne.setForeground(new java.awt.Color(255, 255, 255));
        imageDeleteButtonOne.setText("-\n");
        imageDeleteButtonOne.setFocusPainted(false);
        imageDeleteButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageDeleteButtonOneActionPerformed(evt);
            }
        });
        add(imageDeleteButtonOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, -1, -1));

        imageDeleteButtonTwo.setBackground(new java.awt.Color(102, 0, 0));
        imageDeleteButtonTwo.setFont(new java.awt.Font("HandelGotDLig", 0, 14)); // NOI18N
        imageDeleteButtonTwo.setForeground(new java.awt.Color(255, 255, 255));
        imageDeleteButtonTwo.setText("-\n");
        imageDeleteButtonTwo.setFocusPainted(false);
        imageDeleteButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageDeleteButtonTwoActionPerformed(evt);
            }
        });
        add(imageDeleteButtonTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, -1, -1));

        imageDeleteButtonThree.setBackground(new java.awt.Color(102, 0, 0));
        imageDeleteButtonThree.setFont(new java.awt.Font("HandelGotDLig", 0, 14)); // NOI18N
        imageDeleteButtonThree.setForeground(new java.awt.Color(255, 255, 255));
        imageDeleteButtonThree.setText("-\n");
        imageDeleteButtonThree.setFocusPainted(false);
        imageDeleteButtonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageDeleteButtonThreeActionPerformed(evt);
            }
        });
        add(imageDeleteButtonThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 310, -1, -1));

        jSeparator15.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator15.setForeground(new java.awt.Color(102, 255, 51));
        add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 940, 10));

        importPanel.setBackground(new java.awt.Color(34, 49, 63));
        importPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("House id");
        importPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        jSeparator12.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator12.setForeground(new java.awt.Color(102, 255, 51));
        importPanel.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 10));

        targetHouseIdField.setBackground(new java.awt.Color(34, 49, 63));
        targetHouseIdField.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        targetHouseIdField.setForeground(new java.awt.Color(255, 255, 255));
        targetHouseIdField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        importPanel.add(targetHouseIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, 20));

        jLabel17.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Password");
        importPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 80, -1));

        jSeparator13.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator13.setForeground(new java.awt.Color(102, 255, 51));
        importPanel.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 180, 10));

        targetPasswordField.setBackground(new java.awt.Color(34, 49, 63));
        targetPasswordField.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        targetPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        targetPasswordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        importPanel.add(targetPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 180, 20));

        importButton.setBackground(new java.awt.Color(0, 51, 102));
        importButton.setFont(new java.awt.Font("HandelGotDLig", 0, 14)); // NOI18N
        importButton.setForeground(new java.awt.Color(255, 255, 255));
        importButton.setText("Import");
        importButton.setToolTipText("");
        importButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        importButton.setFocusPainted(false);
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });
        importPanel.add(importButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 90, 30));

        importErrorLabel.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        importErrorLabel.setForeground(new java.awt.Color(51, 255, 255));
        importErrorLabel.setText("import your data");
        importPanel.add(importErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 280, 30));

        add(importPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 840, 70));

        submitButton1.setBackground(new java.awt.Color(0, 153, 0));
        submitButton1.setFont(new java.awt.Font("HandelGotDLig", 0, 18)); // NOI18N
        submitButton1.setForeground(new java.awt.Color(0, 0, 0));
        submitButton1.setText("Submit");
        submitButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        submitButton1.setFocusPainted(false);
        submitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton1ActionPerformed(evt);
            }
        });
        add(submitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 140, 30));

        jLabel244.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel244.setForeground(new java.awt.Color(153, 153, 153));
        jLabel244.setText("House id");
        add(jLabel244, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 70, -1));

        jSeparator16.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator16.setForeground(new java.awt.Color(102, 255, 51));
        add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 180, 10));

        houseIdField.setBackground(new java.awt.Color(34, 49, 63));
        houseIdField.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        houseIdField.setForeground(new java.awt.Color(255, 255, 255));
        houseIdField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        houseIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseIdFieldActionPerformed(evt);
            }
        });
        add(houseIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 180, 20));

        jLabel4545.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4545.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4545.setText("Password");
        add(jLabel4545, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 80, -1));

        jSeparator17.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator17.setForeground(new java.awt.Color(102, 255, 51));
        add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 180, 10));

        passwordField.setBackground(new java.awt.Color(34, 49, 63));
        passwordField.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 180, 20));

        importSuccessfullLabel.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        importSuccessfullLabel.setForeground(new java.awt.Color(51, 255, 255));
        importSuccessfullLabel.setText("data imported !");
        add(importSuccessfullLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGroup(){
        bg1 = new ButtonGroup();
        bg1.add(forRentRadioButton);
        bg1.add(forSaleRadioButton);
        
        bg2 = new ButtonGroup();
        bg2.add(bachelorRadioButton);
        bg2.add(familyRadioButton);
        bg2.add(bothRadioButton);
    }
    
    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        // TODO add your handling code here:              
        downloadData();
    }//GEN-LAST:event_importButtonActionPerformed

    public void clearFields(){
        titleField.setText("");
        areaField.setText("");
        cityField.setText("");
        streetField.setText("");
        postcodeField.setText("");
        descriptionField.setText("");
        ownerNameField.setText("");
        contactNoField.setText("");
        emailField.setText("");
        houseIdField.setText("");
        passwordField.setText("");
        targetHouseIdField.setText("");
        targetPasswordField.setText("");
        priceField.setText("");
        imageLabelOne.setIcon(null);
        imageLabelTwo.setIcon(null);
        imageLabelThree.setIcon(null);
        imagePathOne = null;
        imagePathTwo = null;
        imagePathThree = null;
        adType = null;
        customerType = null;
        targetHouseId = null;
        targetPassword = null;
        roomsComboBox.setSelectedIndex(0);
        belconyComboBox.setSelectedIndex(0);
        bathroomsComboBox.setSelectedIndex(0);
        floorNoComboBox.setSelectedIndex(0);
        monthComboBox.setSelectedIndex(0);
        bg1.clearSelection();
        bg2.clearSelection();
        importPanel.setVisible(true);
        targetHouseIdField.setText("");
        targetPasswordField.setText("");
        importErrorLabel.setText("import your data");
        
       
        
        
    }
    
    
    
    private void downloadData(){
        Connection myConnection = null;
        Statement myStatement  = null;
        ResultSet myResultSet = null;
        ResultSetMetaData myMetaData = null;
        
        
        String sql = "select * from houseAd";
        
        try{
            // get connection to database
            myConnection = DriverManager.getConnection("jdbc:derby://localhost:1527/RentHouseDatabase", "rain013", "oopfinalproject");
            
            // creaTe statement
            myStatement = myConnection.createStatement();
            
            myResultSet = myStatement.executeQuery(sql);
            
            myMetaData = myResultSet.getMetaData();
            
            int columnCount = myMetaData.getColumnCount();
            
            targetHouseId = targetHouseIdField.getText();
            targetPassword = targetPasswordField.getText();
            
            boolean found = false;
            
            while(myResultSet.next())
            {
                if(targetHouseId.equals(myResultSet.getString("houseId")) && targetPassword.equals(myResultSet.getString("password"))){
                    houseIdField.setText(myResultSet.getString("houseId"));
                    titleField.setText(myResultSet.getString("title"));
                    areaField.setText(myResultSet.getString("area"));
                    cityField.setText(myResultSet.getString("city"));
                    streetField.setText(myResultSet.getString("street"));
                    postcodeField.setText(myResultSet.getString("postcode"));
                    roomsComboBox.setSelectedIndex(myResultSet.getInt("rooms"));
                    belconyComboBox.setSelectedIndex(myResultSet.getInt("belcony"));
                    bathroomsComboBox.setSelectedIndex(myResultSet.getInt("bathrooms"));
                    floorNoComboBox.setSelectedIndex(myResultSet.getInt("floorNo"));
                    descriptionField.setText(myResultSet.getString("description"));
                    monthComboBox.setSelectedItem(myResultSet.getString("month"));
                    priceField.setText(myResultSet.getDouble("price")+"");
                    ownerNameField.setText(myResultSet.getString("ownerName"));
                    emailField.setText(myResultSet.getString("email"));
                    passwordField.setText(myResultSet.getString("password"));
                                        
                    blobOne = myResultSet.getBlob("imageOne");
                    if(blobOne != null)
                        imageLabelOne.setIcon(blobToImageIcon(blobOne));                   

                    
                    blobTwo = myResultSet.getBlob("imageTwo");
                    if(blobTwo != null)
                        imageLabelTwo.setIcon(blobToImageIcon(blobTwo));

                    
                    blobThree = myResultSet.getBlob("imageThree");
                    if(blobThree != null)
                        imageLabelThree.setIcon(blobToImageIcon(blobThree));
                    
                    
                    
                    contactNoField.setText(myResultSet.getString("contactNo"));
                    
                    adType = myResultSet.getString("adType");
                    if(adType.equals("sale")){
                        forSaleRadioButton.setSelected(true);
                    }
                    if(adType.equals("rent")){
                        forSaleRadioButton.setSelected(true);
                    }
                    
                    customerType = myResultSet.getString("customerType");
                    if(customerType.equals("bachelor")){
                        bachelorRadioButton.setSelected(true);
                    }
                    if(customerType.equals("family")){
                        familyRadioButton.setSelected(true);
                    }
                    if(customerType.equals("both")){
                        familyRadioButton.setSelected(true);
                    }
                    
                    found = true;
                    
                    
                }
            }
            
            if(found == true){
                importPanel.setVisible(false);
            }
            
            if(found == false){
                importErrorLabel.setText("wrong username or password !");
            }
            
           
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        
    }
    
    private void deletedata(){
        
        Connection myConnection = null;
        PreparedStatement myStatement = null;
        String sql = "Delete from houseAd where houseId=?";
        
        try{
            
            myConnection = DriverManager.getConnection("jdbc:derby://localhost:1527/RentHouseDatabase", "rain013", "oopfinalproject");
            
            myStatement = myConnection.prepareStatement(sql);
            
            myStatement.setString(1, targetHouseIdField.getText());
            
            myStatement.executeUpdate();
            
            System.out.println("old data deleted");
            
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    private void uploadData(){    // this method will upload data to database
        
        Connection myConnection = null;
        PreparedStatement myStatement = null;       
        FileInputStream inputImage = null;
        File theFile = null;
        
        String sql = "insert into houseAd (houseId, title,area, city, street, postcode, rooms, belcony, bathrooms, floorNo, description, month, price, ownerName, email, password, imageOne, imageTwo, imageThree, contactNo, adType, customerType) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        
        
        try {
            // get connection to database
            myConnection = DriverManager.getConnection("jdbc:derby://localhost:1527/RentHouseDatabase", "rain013", "oopfinalproject");
            
            //prepare statement
            myStatement = myConnection.prepareStatement(sql);
           
           // insert data starts 
           myStatement.setString(1, houseIdField.getText());
           myStatement.setString(2, titleField.getText());
           myStatement.setString(3, areaField.getText());
           myStatement.setString(4, cityField.getText());
           myStatement.setString(5, streetField.getText());
           myStatement.setString(6, postcodeField.getText());
           myStatement.setInt(7, Integer.parseInt(roomsComboBox.getSelectedItem().toString()));
           myStatement.setInt(8, Integer.parseInt(belconyComboBox.getSelectedItem().toString()));
           myStatement.setInt(9, Integer.parseInt(bathroomsComboBox.getSelectedItem().toString()));
           myStatement.setInt(10, Integer.parseInt(floorNoComboBox.getSelectedItem().toString()));
           myStatement.setString(11, descriptionField.getText());       
           myStatement.setString(12, Arrays.toString(monthComboBox.getSelectedObjects()));
           myStatement.setDouble(13, Double.parseDouble(priceField.getText()));
           myStatement.setString(14, ownerNameField.getText());
           myStatement.setString(15, emailField.getText());
           myStatement.setString(16, passwordField.getText());
           
           Blob nullBlob = null;
           
           if(imagePathOne == null){             
               
                if(blobOne == null){
                     myStatement.setBlob(17, nullBlob);
                     System.out.println("no");
                 }
                else{
                       myStatement.setBlob(17, blobOne);
                       System.out.println("yes");
                }
           }
           
           else{
               theFile = new File(imagePathOne);
               inputImage = new FileInputStream(theFile);
               myStatement.setBlob(17, inputImage);
           }
           
           if(imagePathTwo == null){ 
               
               if(blobTwo == null){
                     myStatement.setBlob(18, nullBlob);
                     System.out.println("no");
                 }
                else{
                       myStatement.setBlob(18, blobTwo);
                       System.out.println("yes");
                }
               
           }
           else{
               theFile = new File(imagePathTwo);
               inputImage = new FileInputStream(theFile);           
               myStatement.setBlob(18, inputImage);
           }
           
           if(imagePathThree == null){              
               
               if(blobThree == null){
                     myStatement.setBlob(19, nullBlob);
                     System.out.println("no");
                 }
                else{
                       myStatement.setBlob(19, blobThree);
                       System.out.println("yes");
                }
               
           }
           else{
               theFile = new File(imagePathThree);
               inputImage = new FileInputStream(theFile);
               myStatement.setBlob(19, inputImage);
           }
           
           myStatement.setString(20, contactNoField.getText());
           myStatement.setString(21, adType);
           myStatement.setString(22, customerType);
           // insert data finish
           
           int x = myStatement.executeUpdate();         
           
           if(x>0){
               System.out.println("done");
           }
           
           clearFields();           
        
        }
        catch (SQLException e) {
            e.printStackTrace();
        }
        catch (FileNotFoundException ex) {
            Logger.getLogger(EditAdPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    } // finish upload data method
    
    private void imageBrowseButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageBrowseButtonOneActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("*.images", "jpg","gif","png"));
        
        int result = chooser.showOpenDialog(null);
        
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = chooser.getSelectedFile();
            imagePathOne = selectedFile.getAbsolutePath();
            imageLabelOne.setIcon(resizeImageIcon(imagePathOne));
            
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No file selected");
        }
    }//GEN-LAST:event_imageBrowseButtonOneActionPerformed

    private void imageBrowseButtonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageBrowseButtonTwoActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("*.images", "jpg","gif","png"));
        
        int result = chooser.showOpenDialog(null);
        
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = chooser.getSelectedFile();
            imagePathTwo = selectedFile.getAbsolutePath();
            imageLabelTwo.setIcon(resizeImageIcon(imagePathTwo));
            
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No file selected");
        }
    }//GEN-LAST:event_imageBrowseButtonTwoActionPerformed

    private void imageBrowseButtonTheeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageBrowseButtonTheeActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("*.images", "jpg","gif","png"));
        
        int result = chooser.showOpenDialog(null);
        
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = chooser.getSelectedFile();
            imagePathThree = selectedFile.getAbsolutePath();
            imageLabelThree.setIcon(resizeImageIcon(imagePathThree));
            
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No file selected");
        }
    }//GEN-LAST:event_imageBrowseButtonTheeActionPerformed

    private void forRentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forRentRadioButtonActionPerformed
           adType = "rent";
    }//GEN-LAST:event_forRentRadioButtonActionPerformed

    private void bachelorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bachelorRadioButtonActionPerformed
        customerType = "bachelor";
    }//GEN-LAST:event_bachelorRadioButtonActionPerformed

    private void forSaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forSaleRadioButtonActionPerformed
        adType = "sale";
    }//GEN-LAST:event_forSaleRadioButtonActionPerformed

    private void familyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familyRadioButtonActionPerformed
        customerType = "family";
    }//GEN-LAST:event_familyRadioButtonActionPerformed

    private void bothRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bothRadioButtonActionPerformed
        customerType = "both";
    }//GEN-LAST:event_bothRadioButtonActionPerformed

    private void imageDeleteButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageDeleteButtonOneActionPerformed
        imagePathOne = null;
        imageLabelOne.setIcon(null);
        blobOne = null;
    }//GEN-LAST:event_imageDeleteButtonOneActionPerformed

    private void imageDeleteButtonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageDeleteButtonTwoActionPerformed
        imagePathTwo = null;
        imageLabelTwo.setIcon(null);
        blobTwo = null;
    }//GEN-LAST:event_imageDeleteButtonTwoActionPerformed

    private void imageDeleteButtonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageDeleteButtonThreeActionPerformed
        imagePathThree = null;
        imageLabelThree.setIcon(null);
        blobThree = null;
    }//GEN-LAST:event_imageDeleteButtonThreeActionPerformed

    private void submitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton1ActionPerformed
        // TODO add your handling code here:
        deletedata();
        uploadData();
        
    }//GEN-LAST:event_submitButton1ActionPerformed

    private void houseIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_houseIdFieldActionPerformed

    public ImageIcon resizeImageIcon(String imagePath){
        // This method resize & return imageicon from selected path
        
        ImageIcon rawImage = new ImageIcon(imagePath);
        Image img1 = rawImage.getImage();
        Image img2 = img1.getScaledInstance(imageLabelOne.getWidth(), imageLabelOne.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImage = new ImageIcon(img2);
        return newImage;
    }
    
    public ImageIcon blobToImageIcon(Blob blob) {
        
        ImageIcon newImage = null;
        
        try {           
            
            InputStream is = blob.getBinaryStream();
            BufferedImage img1 = ImageIO.read(is);
            Image img2 = img1.getScaledInstance(imageLabelOne.getWidth(), imageLabelOne.getHeight(), Image.SCALE_SMOOTH);
            newImage = new ImageIcon(img2);
            
        } catch (IOException ex) {
            Logger.getLogger(EditAdPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EditAdPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return newImage;
        
    }
    
    
    private String imagePathOne, imagePathTwo, imagePathThree, adType, customerType, targetHouseId, targetPassword;
    private ButtonGroup bg1, bg2;
    private Blob blobOne, blobTwo, blobThree;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaField;
    private javax.swing.JRadioButton bachelorRadioButton;
    private javax.swing.JComboBox<String> bathroomsComboBox;
    private javax.swing.JComboBox<String> belconyComboBox;
    private javax.swing.JRadioButton bothRadioButton;
    private java.awt.Button button1;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField contactNoField;
    private java.awt.TextArea descriptionField;
    private javax.swing.JTextField emailField;
    private javax.swing.JRadioButton familyRadioButton;
    private javax.swing.JComboBox<String> floorNoComboBox;
    private javax.swing.JRadioButton forRentRadioButton;
    private javax.swing.JRadioButton forSaleRadioButton;
    private javax.swing.JTextField houseIdField;
    private javax.swing.JButton imageBrowseButtonOne;
    private javax.swing.JButton imageBrowseButtonThee;
    private javax.swing.JButton imageBrowseButtonTwo;
    private javax.swing.JButton imageDeleteButtonOne;
    private javax.swing.JButton imageDeleteButtonThree;
    private javax.swing.JButton imageDeleteButtonTwo;
    private javax.swing.JLabel imageLabelOne;
    private javax.swing.JLabel imageLabelThree;
    private javax.swing.JLabel imageLabelTwo;
    private javax.swing.JButton importButton;
    private javax.swing.JLabel importErrorLabel;
    private javax.swing.JPanel importPanel;
    private javax.swing.JLabel importSuccessfullLabel;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel244;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4545;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JTextField ownerNameField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField postcodeField;
    private javax.swing.JTextField priceField;
    private javax.swing.JComboBox<String> roomsComboBox;
    private javax.swing.JTextField streetField;
    private javax.swing.JButton submitButton1;
    private javax.swing.JTextField targetHouseIdField;
    private javax.swing.JPasswordField targetPasswordField;
    private javax.swing.JTextField titleField;
    // End of variables declaration//GEN-END:variables
}
