/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrame;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author raino13
 */
public class LittlePanel extends javax.swing.JPanel {

    /**
     * Creates new form LolPanel
     * @param houseID
     * @param title
     * @param area
     * @param city
     * @param adType
     * @param customerType
     * @param price
     * @param image
     */
    public LittlePanel(String houseID, String title, String area, String city,
                       String street, String postcode, int noOfRooms, int noOfBelcony,
                       int noOfBathRooms, int floorNo, String description, String month, Double price,
                       String ownerName, String email, String password, 
                       BufferedImage imageOne, BufferedImage imageTwo, BufferedImage imageThree, 
                       String contactNo, String adType, String customerType ) {
        
        initComponents();
        
        this.houseId = houseID;
        this.title = title;
        this.area = area;
        this.street = street;
        this.city = city;
        this.postcode = postcode;
        this.noOfRooms = noOfRooms;
        this.noOfBelcony = noOfBelcony;
        this.noOfBathrooms = noOfBathRooms;
        this.floorNo = floorNo;
        this.description = description;
        this.month = month;
        this.price = price;
        this.ownerName = ownerName;
        this.email = email;
        this.password = password;
        this.imageOne = imageOne;
        this.imageTwo = imageTwo;
        this.imageThree = imageThree;
        this.contactNo = contactNo;
        this.adType = adType;
        this.customerType = customerType;
                
        titleBar.setText(title);
        locationBar.setText(area+", "+city);
        if("sale".equals(adType)){
            adTypeBar.setText("For sale");
        }
        if("rent".equals(adType)){
            adTypeBar.setText("For rent");
        }
        if("bachelor".equals(customerType)){
            customerTypeBar.setText("For bachelor");
        }
        if("family".equals(customerType)){
            customerTypeBar.setText("For family");
        }
        if("both".equals(customerType)){
            customerTypeBar.setText("For bachelor and family");
        }
        
        priceBar.setText(price.toString()+" taka");
        
        
        Image img = imageOne.getScaledInstance(110, 100, Image.SCALE_SMOOTH);
        ImageIcon ic = new ImageIcon(img);
        imageBar.setIcon(ic);        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locationBar = new javax.swing.JLabel();
        titleBar = new javax.swing.JLabel();
        priceBar = new javax.swing.JLabel();
        adTypeBar = new javax.swing.JLabel();
        customerTypeBar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        imageBar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(34, 49, 63));
        setMinimumSize(new java.awt.Dimension(600, 121));
        setPreferredSize(new java.awt.Dimension(390, 121));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        locationBar.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        locationBar.setForeground(new java.awt.Color(255, 255, 255));
        locationBar.setText("location");
        add(locationBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 195, 30));

        titleBar.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        titleBar.setForeground(new java.awt.Color(255, 255, 255));
        titleBar.setText("title");
        titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleBarMouseClicked(evt);
            }
        });
        add(titleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 195, 30));

        priceBar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        priceBar.setForeground(new java.awt.Color(0, 153, 153));
        priceBar.setText("price");
        add(priceBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 78, -1));

        adTypeBar.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        adTypeBar.setForeground(new java.awt.Color(255, 255, 255));
        adTypeBar.setText("adType");
        add(adTypeBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        customerTypeBar.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        customerTypeBar.setForeground(new java.awt.Color(255, 255, 255));
        customerTypeBar.setText("customerType");
        add(customerTypeBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 51));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 117, 561, -1));

        imageBar.setForeground(new java.awt.Color(204, 204, 204));
        imageBar.setText("          no image");
        imageBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        imageBar.setPreferredSize(new java.awt.Dimension(90, 19));
        add(imageBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 110, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void titleBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMouseClicked
        // TODO add your handling code here:
        showDetail = true;
    }//GEN-LAST:event_titleBarMouseClicked

    String houseId,title,area,city,street,postcode,description,month,ownerName,contactNo,email,adType,customerType;
    private String password;
    double price;
    boolean showDetail = false;
    int noOfRooms, noOfBathrooms, noOfBelcony, floorNo;
    BufferedImage imageOne, imageTwo, imageThree;


    public void setPassword(String password){
	    this.password = password;
    }

    public String getPassword(){
        return password;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adTypeBar;
    private javax.swing.JLabel customerTypeBar;
    private javax.swing.JLabel imageBar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel locationBar;
    private javax.swing.JLabel priceBar;
    private javax.swing.JLabel titleBar;
    // End of variables declaration//GEN-END:variables
}
