/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrame;

import java.awt.CardLayout;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import javax.swing.JOptionPane;

/**
 *
 * @author raino13
 */
public class ManageAdsFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    int xMouse, yMouse;
    
    CreateAdPanel caPanel;
    EditAdPanel eaPanel;
    DeleteAdPanel daPanel;
    
    
    public ManageAdsFrame() {
        initComponents();
        
        caPanel = new CreateAdPanel();
        eaPanel = new EditAdPanel();
        daPanel = new DeleteAdPanel();
        dynamicPanel.setLayout(new CardLayout());
        dynamicPanel.add(caPanel);
        dynamicPanel.add(eaPanel);
        dynamicPanel.add(daPanel);
        caPanel.setVisible(true);
        eaPanel.setVisible(false);
        daPanel.setVisible(false);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        topTitileLabel = new javax.swing.JLabel();
        createAdButton = new javax.swing.JButton();
        editAdButton = new javax.swing.JButton();
        deleteAdButton = new javax.swing.JButton();
        dynamicPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 100));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(34, 49, 63));

        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Minimize Window_48px.png"))); // NOI18N
        minimizeButton.setToolTipText("Minimize");
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseClicked(evt);
            }
        });

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back To_48px.png"))); // NOI18N
        backButton.setToolTipText("Go back home");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        topTitileLabel.setBackground(new java.awt.Color(255, 204, 0));
        topTitileLabel.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        topTitileLabel.setForeground(new java.awt.Color(255, 255, 255));
        topTitileLabel.setText("   RAIN APP");
        topTitileLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topTitileLabelMouseDragged(evt);
            }
        });
        topTitileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topTitileLabelMousePressed(evt);
            }
        });

        createAdButton.setBackground(new java.awt.Color(232, 126, 4));
        createAdButton.setFont(new java.awt.Font("HandelGotDLig", 1, 14)); // NOI18N
        createAdButton.setForeground(new java.awt.Color(0, 0, 0));
        createAdButton.setText("Create Ad");
        createAdButton.setFocusPainted(false);
        createAdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAdButtonActionPerformed(evt);
            }
        });

        editAdButton.setBackground(new java.awt.Color(211, 84, 0));
        editAdButton.setFont(new java.awt.Font("HandelGotDLig", 1, 14)); // NOI18N
        editAdButton.setForeground(new java.awt.Color(0, 0, 0));
        editAdButton.setText("Edit Ad");
        editAdButton.setFocusPainted(false);
        editAdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAdButtonActionPerformed(evt);
            }
        });

        deleteAdButton.setBackground(new java.awt.Color(249, 191, 59));
        deleteAdButton.setFont(new java.awt.Font("HandelGotDLig", 1, 14)); // NOI18N
        deleteAdButton.setForeground(new java.awt.Color(0, 0, 0));
        deleteAdButton.setText("Delete Ad");
        deleteAdButton.setFocusPainted(false);
        deleteAdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAdButtonActionPerformed(evt);
            }
        });

        dynamicPanel.setBackground(new java.awt.Color(0, 102, 102));
        dynamicPanel.setPreferredSize(new java.awt.Dimension(954, 389));

        javax.swing.GroupLayout dynamicPanelLayout = new javax.swing.GroupLayout(dynamicPanel);
        dynamicPanel.setLayout(dynamicPanelLayout);
        dynamicPanelLayout.setHorizontalGroup(
            dynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dynamicPanelLayout.setVerticalGroup(
            dynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(topTitileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minimizeButton)
                        .addGap(18, 18, 18)
                        .addComponent(backButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(createAdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editAdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteAdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(minimizeButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(backButton)))
                    .addComponent(topTitileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteAdButton)
                    .addComponent(editAdButton)
                    .addComponent(createAdButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseClicked

        setState(ManageAdsFrame.ICONIFIED);

    }//GEN-LAST:event_minimizeButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backButtonMouseClicked

    private void topTitileLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topTitileLabelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_topTitileLabelMouseDragged

    private void topTitileLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topTitileLabelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_topTitileLabelMousePressed

    private void editAdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAdButtonActionPerformed
        // TODO add your handling code here:
        caPanel.setVisible(false);
        eaPanel.setVisible(true);
        daPanel.setVisible(false);
        
        eaPanel.clearFields();
    }//GEN-LAST:event_editAdButtonActionPerformed

    private void createAdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAdButtonActionPerformed
        // TODO add your handling code here:
        caPanel.setVisible(true);
        eaPanel.setVisible(false);
        daPanel.setVisible(false);
        
        caPanel.clearFields();
    }//GEN-LAST:event_createAdButtonActionPerformed

    private void deleteAdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAdButtonActionPerformed
        // TODO add your handling code here:
        caPanel.setVisible(false);
        eaPanel.setVisible(false);
        daPanel.setVisible(true);
        
        daPanel.clearFields();
    }//GEN-LAST:event_deleteAdButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAdsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAdsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAdsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAdsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageAdsFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backButton;
    private javax.swing.JButton createAdButton;
    private javax.swing.JButton deleteAdButton;
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JButton editAdButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JLabel topTitileLabel;
    // End of variables declaration//GEN-END:variables
}

